"""create notebooks tables

Revision ID: d82824d86a38
Revises: 3e891c5be1c6
Create Date: 2025-04-13 10:29:12.426974

"""

from alembic import op
import sqlalchemy as sa

from app.models.db import environment, SCHEMA

# revision identifiers, used by Alembic.
revision = "d82824d86a38"
down_revision = "3e891c5be1c6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False
        )

    if environment == "prod":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False
        )

    # ### end Alembic commands ###
